-- MySQL Script generated by MySQL Workbench
-- 04/04/15 00:28:07
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema music_portal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_portal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `music_portal` ;

-- -----------------------------------------------------
-- Table `music_portal`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`artists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artist_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `year` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_albums_artists_idx` (`artist_id` ASC),
  CONSTRAINT `fk_albums_artists`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_portal`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `login` VARCHAR(32) NULL,
  `password` VARCHAR(100) NULL,
  `birthday` DATETIME NULL,
  `gender` TINYINT(1) NULL,
  `country_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_user_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `music_portal`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`tracks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`tracks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `size` DOUBLE NULL,
  `duration` VARCHAR(45) NULL,
  `count_like` INT NULL DEFAULT 0,
  `count_download` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_songs_albums1_idx` (`album_id` ASC),
  INDEX `fk_songs_artists1_idx` (`artist_id` ASC),
  INDEX `fk_tracks_genres1_idx` (`genre_id` ASC),
  INDEX `fk_tracks_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_songs_albums1`
    FOREIGN KEY (`album_id`)
    REFERENCES `music_portal`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_songs_artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_portal`.`artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracks_groups1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_portal`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracks_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `music_portal`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracks_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `music_portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlist_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `music_portal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_portal`.`playlist_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_portal`.`playlist_songs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlist_id` INT NULL,
  `track_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlist_songs_songs1_idx` (`track_id` ASC),
  INDEX `fk_playlist_songs_playlist1_idx` (`playlist_id` ASC),
  CONSTRAINT `fk_playlist_songs_songs1`
    FOREIGN KEY (`track_id`)
    REFERENCES `music_portal`.`tracks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_songs_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `music_portal`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
